services:

  database:
    build: "database"
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - my-network

  simple-api:
    build: "simple-api"
    env_file:
      - .env
    networks:
      - my-network

  httpd:
    build: "http-server"
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:

volumes:
  db-volume :