---
# tasks file for roles/app
- name: Run app container
  docker_container:
    name: simple-api
    image: dorianbqn/tp2-backend:latest
    pull: yes
    state: started
    restart_policy: on-failure
    restart_retries: 3
    networks:
      - name: internal-network
      - name: public-network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
