---
# tasks file for roles/proxy
- name: Run proxy container
  docker_container:
    name: frontend
    image: dorianbqn/tp2-frontend:latest
    state: started
    restart_policy: no
    ports:
      - "80:80"
    networks:
      - name: public-network
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
