name: Deploy App

# on:
#   workflow_run:
#     workflows: ["Build and Push Docker Images"]
#     branches:
#       - main
#     types:
#       - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run Ansible to start apache2 service
      run: |
        ansible all -m service -a "name=apache2 state=started" --private-key=${id_rsa} -u admin --become
