name: Deploy App

# on:
#   workflow_run:
#     workflows: ["Build and Push Docker Images"]
#     branches:
#       - main
#     types:
#       - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run Ansible to start apache2 service
      run: |
        ansible-playbook -i ./ansible/inventories/setup.yml ./ansible/playbook.yml -e "ansible_user=${{ secrets.IP_RSA }}" -e "ansible_host=${{ secrets.SERVER_IP }}"

