name: Deploy App

# on:
#   workflow_run:
#     workflows: ["Build and Push Docker Images"]
#     branches:
#       - main
#     types:
#       - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.ID_RSA }}

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Run Ansible to start apache2 service
      run: |
        ansible all -m service -a "name=apache2 state=started" -u admin --become
      env:
        ANSIBLE_PRIVATE_KEY_FILE: ${{ secrets.ID_RSA }}