name: CI and CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and test with Maven
        run: --file ./TP/TP2/simple-api/pom.xml  mvn clean verify

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend  # adjust if your Dockerfile is in another folder
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp2-backend:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push database image
        uses: docker/build-push-action@v6
        with:
          context: ./TP/TP2/database  # adjust as needed
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp2-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push httpd image
        uses: docker/build-push-action@v6
        with:
          context: ./TP/TP2/http-server # adjust as needed
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp2-frontend:latest
          push: ${{ github.ref == 'refs/heads/main' }}
